version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 80:8000
    volumes:
      - ./backend/app:/opt/app
    environment:
      - FLASK_DEBUG=1
    depends_on:
      - database
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
