version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - 80:8000
    volumes:
      - ./backend/app:/opt/app
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=main.py
  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
